---
title: "How Education Impacts Employment"
date: "9/24/2021"
output: ioslides_presentation
runtime: shiny
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(reshape2)
library(plotly)
```
## Unemployment by Education

```{r eruptions, warning = FALSE}
  unempdoc<-read.csv("Plotly Project Week 3/CGDD25O.csv", header=TRUE)
  unempma<-read.csv("Plotly Project Week 3/CGMD25O.csv", header=TRUE)
  unempba<-read.csv("Plotly Project Week 3/LNS14027662.csv", header=TRUE)
  unempad<-read.csv("Plotly Project Week 3/LNS14027689.csv", header=TRUE)
  unemphs<-read.csv("Plotly Project Week 3/LNS14027660.csv", header=TRUE)
  unemplessh<-read.csv("Plotly Project Week 3/LNS14027659.csv", header=TRUE)
  unempedul<-list(unempdoc, unempma, unempba,unempad,unemphs, unemplessh)
  unempedu<-Reduce(function(x,y) merge(x,y,by="DATE",all=TRUE) ,unempedul)
  colnames(unempedu)<-c("Date","PhD","Master's","Bachelor's","Some College or Associate", "High School", "Some High School")
  unempedu<-unempedu[-(1:96),]
  unempedulong<-melt(unempedu, id.vars = "Date", variable.name = "Educational_Attainment")
  unempedulong$Date<-as.Date(unempedulong$Date, format=" %Y-%m-%d")
  plot_ly(unempedulong, x=~Date, y=~value, color=~Educational_Attainment, type="scatter",mode="line", yaxis = "Rate of Unemployment")%>% layout(yaxis=list(title="Percent Unemployed"))


```


## Labor Force Participation by Education

```{r }
lfparad<-read.csv("Plotly Project Week 3/LNS11327689.csv", header=TRUE)
lfparba<-read.csv("Plotly Project Week 3/LNS11327662.csv", header=TRUE)
lfparhs<-read.csv("Plotly Project Week 3/LNS11327660.csv", header=TRUE)
lfparlessh<-read.csv("Plotly Project Week 3/LNS11327659.csv", header=TRUE)
lfparedul<-list(lfparba,lfparad,lfparhs,lfparlessh)
lfparedu<-Reduce(function(x,y) merge(x,y,by="DATE",all=TRUE) ,lfparedul)
colnames(lfparedu)<-c("Date","Bachelor's+","Some College","High School","Some High School")
lfparedulong<- melt(lfparedu,id.vars = "Date", variable.name = "Educational_Attainment")
lfparedulong$Date<-as.Date(lfparedulong$Date, format=" %Y-%m-%d")
plot_ly(lfparedulong,x=~Date,y=~value,color = lfparedulong$Educational_Attainment,type="scatter",mode="line")%>%layout(yaxis=list(title="Percent of Labor Force Participation"))
```
